### ISSUE TITLE
Logo Proposal 

### ISSUE THREAD

**Issue by dee-y** [Prozi/fluffy#1]
Hi @Prozi, am a graphic designer and i noticed your project does not have a logo. I like your project and would love to contribute a logo to it if you would have me. Logo ideas are welcomed also... 

Best regards, 
Dee-y.

**Comment by nenjack** [comment]
Marvelous. Do it if you want. The project will welcome what you create. Its
opensource anyways (MIT) I will add your creation to the npm package.
Regards and thanks

**Comment by dee-y** [comment]
Hello @Prozi here are my first proposals, decided to go minimal with the logo design...
![fluffy-01](https://user-images.githubusercontent.com/36637989/42562385-8a05d5ba-84f3-11e8-9d70-3717d14232db.png)

Do you like any of these? We can also add or remove something on design. Are there any parts of the design that should be colored? if yes, what color picks?. I am waiting for your suggestions, ideas and comments.

Best Regards,

Dee-y.

**Comment by nenjack** [comment]
I like the one with spyglass most :) :+1:

**Comment by dee-y** [comment]
Lolz great! I prefer it too. Do you have any preferences on the sizes of the logo you need me to export? Or normal is fine

**Comment by nenjack** [comment]
I think a big png like at least 512x512 square with transparent background and some few pixel padding inside so the text doesnt touch the border.

Thank you! :)

**Comment by nenjack** [comment]
colors like pastel blueish spyglass? something friendly like, or maybe greenish or turquoise or orange? I leave that up to you totally!

**Comment by nenjack** [comment]
@dee-y thanks again for the support

**Comment by dee-y** [comment]
I like the way the communication flows really lolz...i assembled all the colors you mentioned with different variants, see any you like?

![fluffy2-01](https://user-images.githubusercontent.com/36637989/42717766-48edda96-86fb-11e8-8de5-9c4733d5889c.png)

more ideas are welcomed please,...

**Comment by nenjack** [comment]
any of 5,6,7,8 which of them do you like best?

**Comment by dee-y** [comment]
I like number 7 best after giving it much thought. So which number are we going ahead with?

**Comment by nenjack** [comment]
@dee-y lets do number 7 then ! :+1: 

also after rethinking I'd like to ask for  not only PNG but also SVG if available as it's better for scaling purpouses, but if you only have PNG no problem too!

**Comment by dee-y** [comment]
No problem @Prozi, will have the logo in PNG and SVG formats for you.

**Comment by nenjack** [comment]
merged @dee-y thanks!
